### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by jtremback** [expr/iso8601-convert#1]
``` js
iso8601.fromDate(Date.now())
TypeError: Object 1425421605297 has no method 'getUTCFullYear'
    at Object.fromDate (/Users/jehan/platform_UIlogger/node_modules/iso8601-convert/index.js:61:21)
    at repl:1:6
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
    at ReadStream.emit (events.js:98:17)
```

Don't know how much more I can say here.

**Comment by jtremback** [comment]
Ah it is a documentation issue.

**Comment by osslate** [comment]
From [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date/now)

> The now() method returns the milliseconds elapsed since 1 January 1970 00:00:00 UTC up until now as a `Number`.

**Comment by osslate** [comment]
Ah, indeed. Nice catch.
